name: Sync Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    # 关键：添加权限声明
    permissions:
      contents: write
    steps:
      - name: Clone Releases from Source
        uses: andrewthetechie/gha-clone-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          src_repo: daimiaopeng/coolapk-desktop
          copy_assets: true
